name: first workflow

on:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps: 
      - name: firstJob script
        shell: cmd
        run: echo Hello World! This is the first job
      - name: chekout
        uses: actions/checkout@v4
      - name: greetings 
        id: greetings
        uses: actions/hello-word-javascript-action@main
        with:
          who-to-greet: 'Mona the Octocat'
      - name: time
        run: |
          echo "The time of the greeting was at: ${{ steps.greetings.outputs.time }}"

  secondjob:
    runs-on: ubuntu-latest
    steps:
      - name: secondJob script
        shell: bash
        run: |
          echo this is the second job
          echo and this is a multi-line script
    
